import course

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='T.A',
                  teacher_name='Ms. Nelson',
                  resource_name='24 hour fitness',
                  resource_url='https://www.24hourfitness.com/'),
    course.Course(period=3,
                  name='English',
                  teacher_name='Mr. Barlas',
                  resource_name='Spark Notes',
                  resource_url='http://www.sparknotes.com/'),
    course.Course(period=4,
                  name='Econ',
                  teacher_name='Mr. Seelbach',
                  resource_name='CNN',
                  resource_url='https://www.cnn.com/'),
    course.Course(period=5,
                  name='Photo 2',
                  teacher_name='Mr. Petterson',
                  resource_name='Photos',
                  resource_url='https://www.reuters.com/news/pictures'),
    course.Course(period=6,
                  name='AVID',
                  teacher_name='Mr. Seelbach',
                  resource_name='AVID',
                  resource_url='https://www.avid.org/'),
]
