import course
import song

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='T.A',
                  teacher_name='Ms. Nelson',
                  resource_name='24 hour fitness',
                  resource_url='https://www.24hourfitness.com/'),
    course.Course(period=3,
                  name='English',
                  teacher_name='Mr. Barlas',
                  resource_name='Spark Notes',
                  resource_url='http://www.sparknotes.com/'),
    course.Course(period=4,
                  name='Econ',
                  teacher_name='Mr. Seelbach',
                  resource_name='CNN',
                  resource_url='https://www.cnn.com/'),
    course.Course(period=5,
                  name='Photo 2',
                  teacher_name='Mr. Petterson',
                  resource_name='Photos',
                  resource_url='https://www.reuters.com/news/pictures'),
    course.Course(period=6,
                  name='AVID',
                  teacher_name='Mr. Seelbach',
                  resource_name='AVID',
                  resource_url='https://www.avid.org/'),
]

TOP_TEN_SONGS = [
    song.Song(title="Love Yourz",
                artist_name= "J.Cole",
                youtube_url= "https://www.youtube.com/embed/VSXJkvQOLP0"),
    song.Song(title= "Power Trip",
                artist_name= "J. Cole",
                youtube_url= "https://www.youtube.com/embed/7AjD7nKiUQ4"),
    song.Song(title= "Beautiful Soul",
                artist_name= "Jesse McCartney",
                youtube_url= "https://www.youtube.com/embed/ek2PDE1cAyY"),
    song.Song(title= "I Want It That Way",
                artist_name= "Backstreet Boys",
                youtube_url= "https://www.youtube.com/embed/4fndeDfaWCg"),
    song.Song(title= "Yo",
                artist_name= "Chris Brown",
                youtube_url= "https://www.youtube.com/embed/yn_6LC4loY8"),
    song.Song(title= "Pineapple",
                artist_name= "Ty Dolla $ign",
                youtube_url= "https://www.youtube.com/embed/CPy0-J6pxKI"),
    song.Song(title= "Bounce Out With That",
                artist_name= "YBN Nahmir",
                youtube_url= "https://www.youtube.com/embed/xVhnfTwh1OA"),
    song.Song(title= "Shang Hai",
                artist_name= "Iamsu",
                youtube_url= "https://www.youtube.com/embed/NwJXEP-9-s4"),
    song.Song(title= "Poetic Justice",
                artist_name= "Kendrick Lamar",
                youtube_url= "https://www.youtube.com/embed/yyr2gEouEMM"),
    song.Song(title= "Always",
                artist_name= "SOB X RBE",
                youtube_url= "https://www.youtube.com/embed/DS-gA9WHDdk"),

]

